export const actionTypes = {
    GET_MOVIES: 'GET_MOVIES',
    GET_MOVIE: 'GET_MOVIE',
    ADD_MOVIE: 'ADD_MOVIE',
    UPDATE_MOVIE: 'UPDATE_MOVIE',
    DELETE_MOVIE: 'DELETE_MOVIE',
    SET_FILTER: 'SET_FILTER',
    SET_SORTER: 'SET_SORTER',
};